### ISSUE TITLE
pycrypto version

### ISSUE THREAD

**Issue by williballenthin** [vivisect/synapse#1]
I think you're from the future?

latest release of `pycrypto` is 2.6.1 (https://www.dlitz.net/software/pycrypto/), but `setup.py` requests `pycrypto>=2.6.2` (https://github.com/vivisect/synapse/blob/master/setup.py#L29).

**Comment by invisig0th** [comment]
hahaha...  how in the world did that happen??!?  I'll push a fix. :)
