### ISSUE TITLE
core.splice RBAC

### ISSUE THREAD

**Issue by aheinz-fe** [vivisect/synapse#24]
Deny (or pend?) any splice the user does not have permissions for, given:
- The user passed to core.splice has already been authenticated by an external mechanism.
- The external mechanism knows the role for any given user.
- The UserAuth cortex has been populated with roles and rules, but not users.

**Comment by invisig0th** [comment]
In your use case, does a user have only one role?  Most of the cortex user stuff assumes users have multiple roles.  Maybe we (ungh) need roles to have roles? ;)

**Comment by invisig0th** [comment]
( if your use case is one-to-one, i'll probably implement a simple API to add a splice via an explicit role )

**Comment by aheinz-fe** [comment]
Yes, a user currently has only one role.

**Comment by invisig0th** [comment]
One last point of clarification...  You *dont* want to be doing your user to role mapping via synapse auth api correct?

**Comment by aheinz-fe** [comment]
Not right now, no. That would require me to synchronize auth info from our external service into synapse (or later replace it with synapse), which is something that I don't want to deal with just yet. Easiest thing for me short term is legacy system for authentication, synapse for authorization.

**Comment by aheinz-fe** [comment]
Per offline discussions, I'm going to implement just-in-time user creation and attach them to appropriate roles. API is already sufficient for this strategy.
