### ISSUE TITLE
subprop types are not registered with the data model

### ISSUE THREAD

**Issue by williballenthin** [vivisect/synapse#44]
subprop types are not registered with the data model. at least, when fetching the property type using `cortex.getPropType('<form>:<subprop>')`, None is always returned.

**Comment by invisig0th** [comment]
from the data model perspective, subprops are meant to be optionally added to the data model ( so you can select which subprops are relevant to your particular model )

**Comment by invisig0th** [comment]
So, users are still meant to call addTufoProp to add the subprops to the model.  we could also make some auto-add subs option to addTufoProp or something.

**Comment by williballenthin** [comment]
ah, ok, thanks! that clears this up.
