### ISSUE TITLE
swarm test for `has` is maybe incorrect

### ISSUE THREAD

**Issue by williballenthin** [vivisect/synapse#55]
i've been teaching myself the swarm syntax using the test cases as a guide. it seems that the test for `has` is simply a duplicate of the test for `save`/`load` (see [here](https://github.com/vivisect/synapse/blob/master/synapse/tests/test_swarm_runtime.py#L290)). is this intended?

**Comment by aheinz-fe** [comment]
I made a pass at documenting it in https://github.com/vivisect/synapse/pull/45

**Comment by williballenthin** [comment]
cool, my documentation is here, btw: https://gist.github.com/williballenthin/9e5891c967004eee8bdf256cbd4f9fcc

**Comment by invisig0th** [comment]
thanks so much.  updated the has test to actually reflect what it was meant to do.
