### ISSUE TITLE
importing synapse from setup.py breaks when msgpack is not installed

### ISSUE THREAD

**Issue by williballenthin** [vivisect/synapse#6]
setup.py imports the synapse module to fetch its version. This breaks in environments when msgpack has not yet been installed.

I often rely on setup.py to declare a package's dependencies so that I can use pip to install it. In minimal environments (like Docker images), msgpack may not yet have been installed, so this workflow breaks. I could fix it on my side by always pre-installing msgpack, but thats not the spirit of setup.py.

One potential fix is to move the version info into setup.py. Unfortunately, then the version info is not available to code.  This feels a little dirty if you *have* to keep another copy of the version info available to code, but at least it works. I've encountered similar issues with my libraries, and taken this shortcut.

**Comment by invisig0th** [comment]
fixed!  thanks! was just trying to be clever about syncing version info... easily fixed.
